version: '3'
services: 
  webserver_imr:
    container_name: webserver_imr
    build:
      context: ../build/laravel
      dockerfile: dev.dockerfile
    ports:
      - 4301:80
    volumes:
      - /webroot/librarymanager:/usr/share/nginx/html:ro
    restart: always
