version: '3'
services:
  mysql:
    container_name: mariadb
    restart: always
    build:
      context: ./build
    ports:
      - 3310:3310
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mysql
