version: '3'
services:
  php_imr:
    container_name: php_imr
    build:
      context: ./build/php
    volumes:
      - /webroot/imr:/var/www/html:ro

  nginx_imr:
    container_name: nginx_imr
    build:
      context: ./build/nginx
    volumes:
      - /webroot/imr:/var/www/html:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/sites/:/etc/nginx/sites-available
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 4304:80
    depends_on:
      - php_imr
    restart: always
